# Generated by Django 5.2.7 on 2025-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_pasajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopasajero',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuariopasajero',
            name='id',
        ),
        migrations.AddField(
            model_name='usuariopasajero',
            name='id_usuario_pasajero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariopasajero',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariopasajero',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuariopasajero',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='usuariopasajero',
            table=None,
        ),
    ]
